-- SET FOLLOWING VARIABLES IN A DO SCRIPT TRIGGER THAT FOLLOWS THE DCS STTS DO SCRIPT FILE


-- FULL PATH TO THE FOLDER CONTAINING DCS-SR-ExternalAudio.exe - EDIT TO CORRECT FOLDER
STTS.DIRECTORY = "C:\\Users\\Ciaran\\Dropbox\\Dev\\DCS\\DCS-SRS\\install-build"

-- LOCAL SRS PORT - DEFAULT IS 5002
STTS.SRS_PORT = 5002

-- GOOGLE CREDENTIALS - FULL PATH TO THE JSON FILE - EDIT TO CORRECT FOLDER (OPTIONAL - ONLY REQUIRED IF USING GOOGLE TTS)
STTS.GOOGLE_CREDENTIALS = "C:\\Users\\Ciaran\\Downloads\\googletts.json"

-- DONT CHANGE THIS UNLESS YOU KNOW WHAT YOU'RE DOING
STTS.EXECUTABLE = "DCS-SR-ExternalAudio.exe"